### ISSUE TITLE
[!] Unable to find a pod matching `FSPagerView`

### ISSUE THREAD

**Issue by jkyeo** [WenchaoD/FSPagerView#1]
Nice work! But:
[!] Unable to find a pod with name, author, summary, or description matching `FSPagerView`

**Comment by jkyeo** [comment]
Well, the latest commit fix the issue. Thanks.

**Comment by WenchaoD** [comment]
@jkyeo I can't searched anything while running the command:
```ruby
pod search FSPagerView
```
I'm still working on the cocoapods stuff. Can you show me your result of running the command?

**Comment by jkyeo** [comment]
@WenchaoD I just search via https://cocoapods.org/?q=FSPagerView. And pod install afftects: "Installing FSPagerView (0.1.0)".
But "pod search FSPagerView" still has no result.
