### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by staticdreams** [WenchaoD/FSPagerView#10]
I see podspec states this framework is only compatible with iOS. Since iOS and tvOS are very similar (especially in regard with commonly used components, such as UICollectionView) would it be possible to implement this component in a tvOS app ? 

I'm talking about a behaviour Apple uses as ad banners in tvOS (App store, Movies etc..)

**Comment by WenchaoD** [comment]
Hi @staticdreams  I've pushed some changes for ***tvOS compatibility***. Please try it.

**Comment by dkcas11** [comment]
I was actually thinking of asking this myself, thanks :) I am gonna test it out as well.
