### ISSUE TITLE
Disable swiping

### ISSUE THREAD

**Issue by RiyanFransen** [WenchaoD/FSPagerView#101]
How is it possible to disable swiping on the FSPager? 

EDIT:
Found a way to do it. You just set the pan gesture recognizer to 0. 
` pagerView.panGestureRecognizer.maximumNumberOfTouches = 0 `

**Comment by nikunjazilen** [comment]
@RiyanFransen Same issue facing by me. When you resolved it please ping me.

**Comment by nikunjazilen** [comment]
@RiyanFransen I can't access panGestureRecognizer of pagerView. Actually, I have imported swift classes in Objective C. Please help
