### ISSUE TITLE
PagerView changing frame size dynamically  

### ISSUE THREAD

**Issue by st-small** [WenchaoD/FSPagerView#11]
Hi! Thank you very much for this awesome framework! But I want to have different sizes images in my PagerView, is it possible? I have CollectionViewController and there I implemented this moment (each image in array calculated sizes and sent them to collectionView), but here I can't get the view with custom size for each image... I think that one way to get it this is make images aspectFill, but I want to get more quality images in my app... 

TNX

**Comment by dkcas11** [comment]
Would it be possible to set the size, ie. change it, every time you create your cell?

**Comment by st-small** [comment]
@dkcas11 I recieve JSON, parse and have many items with photos, I want to show all of them in pageControl with animation (like a promo of goods). Photos have different sizes (also, landscape and portrait orientations). When I make collectionView, I put all photos in array with custom size (I calculated it from static height). Code is bellow. And make the cell of collectionView that size, that the photo has. I want to do the same with self.pageControl, is it really?

`- (UIImage*)resizingImage:(UIImage*)image {
    
    CGFloat scaleFactor = targetHeight / image.size.height;
    CGFloat targetWidth = image.size.width * scaleFactor;
    CGSize targetSize = CGSizeMake(targetWidth, targetHeight);
    UIImage* scaledImage = [SiSCollectionViewController imageWithImage:image scaledToSize:targetSize];
    
    return scaledImage;
}

+ (UIImage *)imageWithImage:(UIImage *)image scaledToSize:(CGSize)newSize {
    UIGraphicsBeginImageContextWithOptions(newSize, NO, 0.0);
    [image drawInRect:CGRectMake(0, 0, newSize.width, newSize.height)];
    UIImage *newImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return newImage;
}`

**Comment by st-small** [comment]
I want to have pagerView size only for image (without white color by sides)
![2017-02-22 21 29 16](https://cloud.githubusercontent.com/assets/1850189/23228690/21a700aa-f946-11e6-9bfa-1c76f368b4b2.png)

**Comment by dkcas11** [comment]
Well one thing you could do, is scale all images to have the same width, but varying height. This way you ensure that the correct content is always displayed to the user.
I haven't tried it, but maybe you can use the [_itemSize_](https://github.com/WenchaoD/FSPagerView#itemsize) in the _ cellForItemAt_ delegate function, before you return the cell, with its size applied to the pagerView.
Otherwise, you will have to subclass the FSPagerViewCell and make your own that supports this.

**Comment by st-small** [comment]
@dkcas11 Thank you very much for help but I can't understand what I should to do with itemSize. I set it property in cell making method and it show other photos incorrect. I add video to show how it works. May be I should to check if it current photo then change itemSize if no - reload itemSize (or use the default sizes)...

[https://yadi.sk/i/82ZJbqRZ3ESpSz](url)

**Comment by dkcas11** [comment]
I see.. I think you will have to subclass FSPagerViewCell and create the cell yourself, in order to support this.

**Comment by st-small** [comment]
@dkcas11 This is so hard to me, because I make the project with Objective-C language but the framework is on Swift written. It is so difficult level for me to make Objective-C class by subclass of swift. So I'll use it with aspectFill images. Looks so nice.

![2017-02-24 19 24 52](https://cloud.githubusercontent.com/assets/1850189/23313579/00d627de-fac7-11e6-9fd2-85d8d37eaafb.png)
