### ISSUE TITLE
How to disable Manual Scrolling

### ISSUE THREAD

**Issue by rfgallagher1** [WenchaoD/FSPagerView#114]
I'd like to disable manual scrolling during certain times, but leave items inside the cell clickable.

This means I can't do userInteractionEnabled = false on the whole pagerview, because it'll block my cell interactions.

Thanks

**Comment by rfgallagher1** [comment]
Not sure what the PR situation is here, but if this one new method would do it in FSPagerView:
`  @objc(enableScrolling:)
    open func enableScrolling(_ isEnabled : Bool){
        self.collectionView.isScrollEnabled = isEnabled
    }`

**Comment by hai2014bk** [comment]
@rfgallagher1 where should i put it to ??

**Comment by rfgallagher1** [comment]
Put it in FSPagerView.swift

That means you can't pull this in with CocoaPods. Take the file and manually add it to your project, so you can edit the file.

I put the method around line 516, right above commonInit().

@hai2014bk Sorry for the late response, hope that helps

**Comment by WenchaoD** [comment]
```swift
pagerView.isScrollEnabled = false.
```
