### ISSUE TITLE
cellForItemAt not called!

### ISSUE THREAD

**Issue by arsanjani** [WenchaoD/FSPagerView#12]
Hi there
i wanna to implement fspagerview in tableHeaderView of uitableview. after pagerView.reloadData() cellForItemAt... not called but numberOfItems fired !!  

`

        let nib = UINib(nibName: "BannerViewNew", bundle: nil)
        self.newsListTableView.register(nib, forHeaderFooterViewReuseIdentifier: "BannerViewNew")
        let cell = self.newsListTableView.dequeueReusableHeaderFooterView(withIdentifier: "BannerViewNew") as! BannerViewNewCell
        cell.frame = CGRect(x: 0.0, y: 0.0, width: self.newsListTableView.frame.width, height: 250.0)
        cell.pagerView.frame = cell.frame
        cell.pagerView.delegate = self
        cell.pagerView.dataSource = self
        cell.pageControl.numberOfPages = bannerList?.count ?? 0
        cell.pagerView.reloadData()
        self.newsListTableView.tableHeaderView = cell`

**Comment by WenchaoD** [comment]
Hi @arsanjani Can you try the latest code in the `master` branch? If this problem still exists, can you provide a demo project link which reproduce and demonstrate this issue?

**Comment by WenchaoD** [comment]
Fixed in `0.2.1`. Please try again. Thanks.
