### ISSUE TITLE
How to add JSON data to FSPagerView dynamically?

### ISSUE THREAD

**Issue by Prashanna7** [WenchaoD/FSPagerView#122]
Here is my JSON data 

[
    {
        "featured_img": "http://www.swipecrafts.com/uploads/school/featured_img/image_1.jpg"
    },
    {
        "featured_img": "http://www.swipecrafts.com/uploads/school/featured_img/image_2.jpg"
    },
    {
        "featured_img": "http://www.swipecrafts.com/uploads/school/featured_img/image_3.jpg"
    },
    {
        "featured_img": "http://www.swipecrafts.com/uploads/school/featured_img/image_4.jpg"
    },
    {
        "featured_img": "http://www.swipecrafts.com/uploads/school/featured_img/image_5.png"
    }
]
I tried to add these images using different method but could not succeed in doing so, can any one help me? OR the data to this page view is only be used statically?

**Comment by s9134131** [comment]
you can parse these json in advance, and set them into imageNames array.
reload data by calling pagerView.reloadData(),
finally, you could fetch image in pagerView(_ pagerView: FSPagerView, cellForItemAt index: Int) -> FSPagerViewCell by tools like Alamofire or others that can load image from url asynchronized (also can pre-fetch image and change imagesNames array into images with UIImage type.)

**Comment by WenchaoD** [comment]
@s9134131 's solution will work.
