### ISSUE TITLE
FSPagerView.scrollDirection no more visible in Objective-C 

### ISSUE THREAD

**Issue by ugochirico** [WenchaoD/FSPagerView#125]
in the last version 0.7.1 suddenly the property scrollDirection is no more visible in Objective-C.

to be visible in Objective-C the property should be declared using @IBInspectable
 
```
@IBInspectable
open var scrollDirection: FSPagerViewScrollDirection ...
```
Can you fix?

**Comment by WenchaoD** [comment]
Try `0.8.0`.
