### ISSUE TITLE
Set the size for the selected page indicator

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [WenchaoD/FSPagerView#127]
This is a feature request. A sort of a nice-to-have one.

A way to set the size for the selected page indicator in the page control. Something like this.

![fullsizerender 28](https://user-images.githubusercontent.com/2551877/38636516-076d41e6-3de6-11e8-8782-6bd723126f7d.jpg)

**Comment by WenchaoD** [comment]
```swift
pageControl.setPath:{aSmallPath} forState:UIControlStateNormal
pageControl.setPath:{aLargePath} forState:UIControlStateNormal
```
Where `{aSmallPath}` is small indicator, and `{aLargePath}` is your large one.
