### ISSUE TITLE
"currentPage" is not availanle/does not exist

### ISSUE THREAD

**Issue by aravasio** [WenchaoD/FSPagerView#133]
The documentation mentions such a property (Alongside of "numberOfPages", which does indeed exist), yet it's nowhere to be found.

The closest I could find to it is `currentIndex`, which is private(set) only.

Did something happen?

**Comment by WenchaoD** [comment]
As it mentions in Readme, `numberOfPages` is a property of `FSPageControl`, **NOT** `FSPagerView`.
