### ISSUE TITLE
Storyboard error 

### ISSUE THREAD

**Issue by jose920405** [WenchaoD/FSPagerView#142]
this error started to happen after installing this module with pod.

```
IB Designables: Failed to render and update auto layout status for myController (fLq-9I-Zau): dlopen(FSPagerView.framework, 1): no suitable image found.  Did find:
  FSPagerView.framework: required code signature missing for 'FSPagerView.framework'
```

and causes rendering problems in the storyboard.

Example: 

![captura de pantalla 2018-05-22 a la s 3 48 42 p m](https://user-images.githubusercontent.com/12536184/40389407-f9d9b58e-5dd7-11e8-96b0-fc827fb73d11.png)

Uninstalling this module fix the problem.

Xcode 9.2
Swift 4

**Comment by TaugyStyle** [comment]
Same situation here  :( If someone has a solution , ty

**Comment by jose920405** [comment]
Check this topic in another library.

it seems to be a CocoaPods error.

https://github.com/luispadron/UICircularProgressRing/issues/84

**Comment by efriandika** [comment]
I get this problem as well. is there any solution ?

**Comment by WenchaoD** [comment]
Have you tried [this solution](https://github.com/WenchaoD/FSCalendar/issues/914)?

**Comment by efriandika** [comment]
Wow.. it works :D thank you @WenchaoD
