### ISSUE TITLE
PrepareForReuse problem

### ISSUE THREAD

**Issue by dunqi** [WenchaoD/FSPagerView#15]
Hey, 

I have a custom cell, to display my own view. But the views, that are used later in queue weren't rendered correctly. I use "prepareForReuse" to use less memory and rerender, if views are shown, but the views are stuck, like they are cached or something. In normal collectionView, it works perfectly, so I think, it just appeared, since I used FSPagerView.

**Comment by WenchaoD** [comment]
Hi @dunqi Can you provide a demo project which reproduces this issue?
