### ISSUE TITLE
View added to cell has shadow

### ISSUE THREAD

**Issue by justdan0227** [WenchaoD/FSPagerView#153]
So I'm attempting to add a UIView on top of an image in my xib, and for some reason the UIView has a shaddow around it?

**Comment by WenchaoD** [comment]
The `cell.contentView` has a shadow around it. You can turn it off by
```swift
cell.contentView.layer.shadowRadius = 0
cell.contentView.layer.shadowOpacity = 0
```

**Comment by justdan0227** [comment]
Thanks.. you ROCK!
