### ISSUE TITLE
pagerViewWillEndDragging sometimes returns out of bounds index

### ISSUE THREAD

**Issue by c0state** [WenchaoD/FSPagerView#154]
I've noticed that when I'm on the first element of the pager and I bounce drag right (since there are no more elements), I get a targetIndex of -1. It seems like there should be a check to see if the pager is on the first or last element.

The same occurs on the last element of the pager and I "bounce" drag left.

Is this done on purpose to indicate that the user is trying to scroll past the pager bounds?

**Comment by WenchaoD** [comment]
Try `0.8.0`.
