### ISSUE TITLE
Storyboard Error 

### ISSUE THREAD

**Issue by DeevD** [WenchaoD/FSPagerView#155]
Main.storyboard: error: IB Designables: Failed to render and update auto layout status for HomeVC (ei9-EM-uZZ): Failed to load designables from path (null)

Anyone !!

**Comment by SirComet** [comment]
its mostly because of other library using @designable or overriding methods. just remove the @designable tag from the source/pods.

**Comment by Sophie1214** [comment]
Create a new class inheriting the FSPagerView class, and use the new class

**Comment by DeevD** [comment]
nice bro thank
