### ISSUE TITLE
加入到自定义 UICollectionViewCell 中 ，作为UICollectionView的 headerview 则无法手动滑动

### ISSUE THREAD

**Issue by tosslife** [WenchaoD/FSPagerView#16]
我自定义了一个headerView ：UICollectionViewCell 然后在其中添加 banner: FSPagerView
但是 添加后正常显示 但是无法手动滚动 接收事件 请教会是哪里的问题呢？
部分代码如下
//
 lazy var banner: FSPagerView = {
        let pagerView = FSPagerView(frame: CGRect(x: 0, y: 0, width: Constant.screenWidth, height: ConstantValue.bannerH))
        pagerView.register(FSPagerViewCell.self, forCellWithReuseIdentifier: "cell")
        pagerView.transformer = FSPagerViewTransformer(type: .overlap)
        let transform = CGAffineTransform(scaleX: 0.7, y: 0.85)
        pagerView.itemSize = pagerView.frame.size.applying(transform)
        pagerView.automaticSlidingInterval = 3.0
        pagerView.isInfinite = true
        pagerView.delegate = self
        pagerView.dataSource = self
        
        return pagerView
    }()
    
    //顶部容器
    lazy var headerView: UIView = {
        let headerView = UIView(frame: CGRect(x: 0, y: 0, width: self.view.bounds.width, height: ConstantValue.headerH))
        headerView.backgroundColor = UIColor.blue
        headerView.addSubview(self.banner)
        return headerView
    }()
    
    lazy var layout: UICollectionViewFlowLayout = {
        let layout = UICollectionViewFlowLayout()
        layout.minimumLineSpacing = ConstantValue.cellMargin
        layout.minimumInteritemSpacing = ConstantValue.cellMargin
        
        layout.scrollDirection = .vertical
        layout.sectionInset = UIEdgeInsets(top: ConstantValue.cellMargin, left: ConstantValue.cellMargin, bottom: ConstantValue.cellMargin, right: ConstantValue.cellMargin)
        layout.headerReferenceSize = CGSize(width: self.view.bounds.width, height: ConstantValue.sectionHeaderHeight)
        return layout
    }()
    
    
    lazy var collectionView: UICollectionView = {
        let collectionView = UICollectionView(frame: self.view.bounds, collectionViewLayout: self.layout)
        collectionView.register(HeaderViewCell.self, forCellWithReuseIdentifier: CellIdentifier.headerCell.rawValue)
        collectionView.register(UINib(nibName: String(describing: SpreadViewCell.self), bundle: nil), forCellWithReuseIdentifier: CellIdentifier.spreadCell.rawValue)
        
        collectionView.delegate = self
        collectionView.dataSource = self
        return collectionView
    }()

**Comment by tosslife** [comment]
抱歉 忘了设置headerview的高度

**Comment by Daletar** [comment]
记录一下，我也碰到类似的问题。我是添加在UITableViewCell中。直接self.addSubiew,  需要添加在cell的contentView中。
