### ISSUE TITLE
OC 怎么自定义Cell

### ISSUE THREAD

**Issue by Suzhibin** [WenchaoD/FSPagerView#166]
- (FSPagerViewCell *)pagerView:(FSPagerView *)pagerView cellForItemAtIndex:(NSInteger)index

我想到的是继承FSPagerViewCell  可是 混编一直报错 查了查 好像OC不能继承swift 的类 请问 @WenchaoD 如何解决？

建议作者把返回的cell 设置为 UICollectionViewCell  这样自定义就方便了
- (UICollectionViewCell *)pagerView:(FSPagerView *)pagerView cellForItemAtIndex:(NSInteger)index

**Comment by YQRush** [comment]
现在OC要想使用自定义的cell，就只能先改内部代码了

**Comment by Suzhibin** [comment]
好的 @YQRush
