### ISSUE TITLE
FSPagerViewCell相关的处理 是否可以改为协议类型或泛型, 以更好的支持自定义Cell类型

### ISSUE THREAD

**Issue by lixiang1994** [WenchaoD/FSPagerView#167]

**Comment by WenchaoD** [comment]
FSPagerViewCell的处理方式将与UICollectionViewCell的处理方式尽量保持一致。

**Comment by lixiang1994** [comment]
继承的方式对于使用自定义cell来说并不方便, 建议delegate方法的返回值不如改成协议 这样自定义cell将不受FSPagerViewCell的影响

**Comment by lixiang1994** [comment]
可以是一个继承UICollectionViewCell的协议, 这样自定义cell只需实现该协议即可, 不必继承FSPagerViewCell, 还要考虑父子类的问题, 假如你未来版本中FSPagerViewCell进行了修改, 还可能影响子类的效果

**Comment by lixiang1994** [comment]
类似这样子
```
protocol FSPagerViewCellable: NSObjectProtocol {
    /// 你需要让cell实现的方法等等
    func xxxx()
}
typealias FSPagerViewCell = (UICollectionViewCell & FSPagerViewCellable)

func pagerView(_ pagerView: FSPagerView, cellForItemAt index: Int) -> FSPagerViewCell
```

**Comment by WenchaoD** [comment]
你好，感谢您的建议。
如果这样做也可以解决问题，但若用户想要自定义单元格，就必须与`FSPagerViewCellable`协议以及FSPagerView中实际依赖的`UICollectionViewCell`两个部分发生作用，这显然是违背了迪米特法则。
我们应当尽量减少用户使用时可能造成的认知负担。

**Comment by lixiang1994** [comment]
emmm... 我觉得继承`UICollectionViewCell `是必然的, 毕竟你是基于UICollectionView做的, 主要是继承Cell对于自定义来说很不友好, 我想写一个不一样的Cell 还要受父类影响 考虑父类里做了什么 我要不要避免什么, 对于Swift来说 更提倡利用协议来解决, 相比于继承来说更加灵活 扩展性更高. 您觉得呢? 这点您可以参考一下Swift标准库的设计 几乎都是由协议/扩展组成. 我只是觉得Swift的库应该有Swift的特色, 而不是和OC一样, 那Swift将没有任何意义了

**Comment by ghostlordstar** [comment]
我就想问问，怎么取消点击时的灰色蒙版？🌚，很上头，这效果为啥不让改，为啥非要继承与FSPagerViewCell。。。

**Comment by ghostlordstar** [comment]
完全可以给个空父类的实现

**Comment by lixiang1994** [comment]
@ghostlordstar 哈哈哈

**Comment by chuheridangwu** [comment]
不能自定义cell好不方便

**Comment by lixiang1994** [comment]
[PagerWrapperCell.swift.zip](https://github.com/WenchaoD/FSPagerView/files/9738914/PagerWrapperCell.swift.zip)

我写了个泛型包装类, 可以拿去参考一下

<img width="907" alt="image" src="https://user-images.githubusercontent.com/13112992/194701426-9ffe646e-f5b7-429b-a8b0-9362e3abf2a6.png">
