### ISSUE TITLE
点击后整个cell 会变灰,感觉盖了一个蒙层, 能不能把这个效果去掉?

### ISSUE THREAD

**Issue by cocfident** [WenchaoD/FSPagerView#168]
如题

**Comment by WenchaoD** [comment]
请查看相关delegate方法。
![image](https://user-images.githubusercontent.com/5186464/45736050-68e8e600-bc1c-11e8-81c1-f620b7766fd8.png)

**Comment by Smeegol** [comment]
@WenchaoD 同样的问题。shouldHighlightItemAt返回false之后，引起新的问题：不能响应点击事件了。有没有更好的方式
