### ISSUE TITLE
使用instrument 发现fspagerview一直在增加内存的使用

### ISSUE THREAD

**Issue by EmersonWill** [WenchaoD/FSPagerView#169]
persistent bytes 一直在增加
![2018-09-15 6 28 57](https://user-images.githubusercontent.com/27496793/45585365-b6f8a380-b915-11e8-8610-978d4dc0ead8.png)
一直在copy这个layout...
![2018-09-15 6 28 00](https://user-images.githubusercontent.com/27496793/45585366-b6f8a380-b915-11e8-9181-aaffb7c22704.png)

**Comment by WenchaoD** [comment]
你好，请确定你的使用是否与Demo中的使用方式有出入。
下图为在demo中无限循环模式下连续滑动几十次的结果。
![image](https://user-images.githubusercontent.com/5186464/45735868-f1b35200-bc1b-11e8-90dc-fe88dcc75255.png)
这个Size值只因为copy增加了7次，正好为demo中轮播item的数量。
