### ISSUE TITLE
引用异常

### ISSUE THREAD

**Issue by Eddiegooo** [WenchaoD/FSPagerView#18]
你好！手动拖FSPagerView 这个文件夹到工程，不能正常使用呢，找不到FSPagerView这个类，引用不了。
使用CocoaPods安装，找不到FSPagerControl 那个类，import不了。
PS：可否公开下实现方式的代码。 还有怎么实现的FSPagerView类像是系统类（在xcode 里显示是蓝色字体）的？ O(∩_∩)O谢谢 开源！

**Comment by WenchaoD** [comment]
* 拖拽的文件夹应该是`Sources`. README.md已修改。
* 在OC中使用Swift类库，引用语句是`#import ProductModuleName-Swift.h`. 其中ProductModuleName默认是Product Name，用`_`代替特殊字符。例如在OC的demo（FSPagerViewExample-Objc）中import语句是`#import "FSPagerViewExample_Objc-Swift.h"`。详情可以参照[Product 模块命名](https://github.com/CocoaChina-editors/Welcome-to-Swift/blob/master/Using%20Swift%20with%20Cocoa%20and%20Objective-C/03Mix%20and%20Match/Swift%20and%20Objective-C%20in%20the%20Same%20Project.md#product-模块命名)。
* 在OC中引用Swift类库会显示蓝色字体。

**Comment by Eddiegooo** [comment]
非常感谢！ 我再去看看 O(∩_∩)O谢谢
