### ISSUE TITLE
Thread 1: Fatal error: index 1 is out of range [0...-1] line 511 of FSPagerView.swift

### ISSUE THREAD

**Issue by deafjam** [WenchaoD/FSPagerView#187]
I will try scrollToItem after reloadData (), it seems reloadData () does not update the data, because numberOfItems is 0.

**Comment by deafjam** [comment]
solved: run scrollToItem in main tread
`
DispatchQueue.main.async {
            self.pagerView!.scrollToItem(at: selectedAvatarIndex, animated: false)
        }
`

**Comment by kornha** [comment]
still get this bug:
        self.photoPagerView.reloadData()
        DispatchQueue.main.async {
            self.photoPagerView.scrollToItem(at: self.selectedCellIndex, animated: false)
        }

**Comment by lvandyk** [comment]
Using @deafjam solution makes it work, but `Thread.isMainThread` is true already. I'm doing it on viewDidLoad. Very strange.
