### ISSUE TITLE
I can't switch off selection color.

### ISSUE THREAD

**Issue by Willianlike** [WenchaoD/FSPagerView#189]
Please add "selectionStyle", or color and alpha for it. I can't switch off selection color.

**Comment by fadiBlessedTree** [comment]
You can use this trick to remove selection color but the cell will not clickable any more, you can use same function for click functionality 

func pagerView(_ pagerView: FSPagerView, shouldSelectItemAt index: Int) -> Bool {
        return false
    }

**Comment by sashakid** [comment]
@WenchaoD Why have you closed it if the problem isn't solved? It's needed to control selection color or disable it at all but still keep the selection possible.

**Comment by Willianlike** [comment]
@sashakid I did the pull request. So you can fork the project and than make the same commit. It helped me. https://github.com/WenchaoD/FSPagerView/pull/249
