### ISSUE TITLE
Problem with installing with pods

### ISSUE THREAD

**Issue by tereznikov** [WenchaoD/FSPagerView#20]
1.  If just try to use:` pod 'FSPagerView'` we see the error in terminal: 
[!] Unable to find a specification for `FSPagerView`.
Resolved with try to use pod with a link to git repository like this:
`pod 'FSPagerView', :git => 'https://github.com/WenchaoD/FSPagerView.git'`

2. And when I add this lib, and try to `FSPagerView` to storyboard I have a warning:
<img width="393" alt="2017-03-05 1 00 15" src="https://cloud.githubusercontent.com/assets/17447829/23582655/484bdd46-0140-11e7-97d1-bab4bd6ee044.png">
And app will crush when try to open it. I've also resolve this problem adding module to view setting in storyboard
<img width="261" alt="2017-03-05 1 07 05" src="https://cloud.githubusercontent.com/assets/17447829/23582672/86e122c8-0140-11e7-92d4-2444e1783ab2.png">

**Comment by saldous** [comment]
1) pod repo update should resolve that, did for me
2) I had same issue, this information is missing in the readme

**Comment by tereznikov** [comment]
@saldous the first problem was resolved with pod repo update (thank you I really don't know about this pod function)
