### ISSUE TITLE
Swift 4.2 Update

### ISSUE THREAD

**Issue by seenoevo** [WenchaoD/FSPagerView#209]
Can **FSPagerView** be updated for Swift 4.2?

I'm getting the following warning:
![untitled](https://user-images.githubusercontent.com/8109158/52927212-3f78d700-32ee-11e9-830a-e4e1564f9806.png)

Thanks!

**Comment by SalvoSwift21** [comment]
Hi, how much do you have this warning? I tried to build both the library and the example with xCode 10.1 / Swift 4.2, and I found no problem.

**Comment by seenoevo** [comment]
@SalvoSwift21 thanks for checking

Unfortunately I'm not sure anymore. I got this warning when I first started migrating my code from Swift 4 -> 4.2 and began replacing another library with this one.

However, I have fixed all errors and warnings in my code related to 4.2 and for some reason, this warning disappeared. 🎉

**Comment by SalvoSwift21** [comment]
Ok, perfect.
