### ISSUE TITLE
Enhancement request: Limit scroll to 1 index at a time

### ISSUE THREAD

**Issue by saldous** [WenchaoD/FSPagerView#21]
I didn't see this in the Readme, if a user swipes the screen quickly, it can scroll multiple indexes. Is it possible to make it only scroll 1 index at a time, please?

**Comment by JoeSzymanski** [comment]
I ran into this problem, also. I'm going to see if there's anything that can be done to fix this.

I've also seen a case where the end position isn't exactly at one of the photo positions, and I think it might be related.

**Comment by JoeSzymanski** [comment]
Should be fixed with #22

**Comment by WenchaoD** [comment]
@JoeSzymanski @saldous Thanks for submitting the issue and the pull request. I've been thinking about this issue. Limiting the scrolling index to 1 could be a good performance if the `itemSize` is the same as the parent (the pager view), not if the `itemSize` is small. Probably you'll get the idea if you open `App Store` in your iPhone and try flipping the items fast in home page, or the `screenshots` in detail page.

**Comment by JoeSzymanski** [comment]
I didn't think about that specifically, but at the same time, I did make my fix require turning the feature on. The default behavior remains in place without the developer choosing to limit scrolling to one page at a time.

**Comment by saldous** [comment]
Thanks, agreed, should be optional so developer can decide if they want this behavior or not.

**Comment by saldous** [comment]
@JoeSzymanski I'm seeing multiple issues with the fix you provided. Doesn't seem to have been done against latest version?

**Comment by JoeSzymanski** [comment]
It was done against master a few days ago. I just merged the latest changes in and resolved the one conflict. Please check it again.

**Comment by JoeSzymanski** [comment]
I'm not sure how easily I'll be able to get this 100% functional. It works well for horizontal mode if the item size approximately matches the screen size. For the quick testing of the vertical case, this is much less likely, and has the problems @WenchaoD was referencing earlier. I don't know what the best way to deal with that is, even though I know I need the basic case for full-screen horizontal paging to be able to make use of the library.

I'm open to suggestions on how to resolve these problems.

**Comment by satishVekariya** [comment]
@WenchaoD I have idea to limit one item plz refer my below code 

    ```
fileprivate var offsetAtBegin:CGPoint?
    public func scrollViewDidScroll(_ scrollView: UIScrollView) {
        if let offset = offsetAtBegin {
            let pageSide:CGFloat = collectionViewLayout.itemSpacing
            if scrollView.contentOffset.x > offset.x + pageSide {
                scrollView.contentOffset.x = offset.x + pageSide
            } else if scrollView.contentOffset.x < offset.x - pageSide {
                scrollView.contentOffset.x = offset.x - pageSide
            }
        }
        if self.numberOfItems > 0 {
            // In case someone is using KVO
            let currentIndex = lround(Double(self.scrollOffset)) % self.numberOfItems
            if (currentIndex != self.currentIndex) {
                self.currentIndex = currentIndex
            }
        }
        guard let function = self.delegate?.pagerViewDidScroll else {
            return
        }
        function(self)
    }
    
    public func scrollViewWillBeginDragging(_ scrollView: UIScrollView) {
        if let function = self.delegate?.pagerViewWillBeginDragging(_:) {
            function(self)
        }
        if self.automaticSlidingInterval > 0 {
            self.cancelTimer()
        }
        offsetAtBegin = scrollView.contentOffset
    } 

  public func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
        if let function = self.delegate?.pagerViewDidEndDecelerating {
            function(self)
        }
        offsetAtBegin = nil
  }
```

**Comment by WenchaoD** [comment]
Close as already implemented.
