### ISSUE TITLE
Update swift(5) version

### ISSUE THREAD

**Issue by satishVekariya** [WenchaoD/FSPagerView#220]

**Comment by speeddream** [comment]
conversion to Swift5 is available

![372FC77D-CE8C-41D5-8E40-3BA1BAF1826D](https://user-images.githubusercontent.com/10609051/57501040-8936f380-7318-11e9-9c6f-0b3cff50ee08.png)

**Comment by WenchaoD** [comment]
Fixed. Thanks.
