### ISSUE TITLE
FSPagerViewCell index

### ISSUE THREAD

**Issue by tereznikov** [WenchaoD/FSPagerView#23]
As I understood there is no way to find FSPagerViewCell index path.

**Comment by WenchaoD** [comment]
Try [this](https://github.com/WenchaoD/FSPagerView/commit/f84475acf7b8b3ed30946569ba7a5172b65c6b1f)?

**Comment by tereznikov** [comment]
@WenchaoD oh nice! super, thank you:)

**Comment by tereznikov** [comment]
@WenchaoD Could you upload this fix to the current version of FSPagerView pod. Because in version 0.4 I didn't see this fix. Thank you!

**Comment by WenchaoD** [comment]
Try `0.4.1`.
<img width="561" alt="screen shot 2017-03-16 at 5 06 02 pm" src="https://cloud.githubusercontent.com/assets/5186464/23988815/e0a74570-0a6a-11e7-8781-92dfc3433f21.png">
