### ISSUE TITLE
Custom Cell makes didSelectItemAt unwork

### ISSUE THREAD

**Issue by xinnai** [WenchaoD/FSPagerView#245]
I follow the tips to create a custom cell 

Create a CustomCollectViewCell and dont forget to inherit FSPagerViewCell

Register cell: pagerView.register(UINib(nibName: "YourCustomCell", bundle: nil), forCellWithReuseIdentifier: "YourCustomCell")

In the impplement datasource:
func pagerView(_ pagerView: FSPagerView, cellForItemAt index: Int) -> FSPagerViewCell {
let cell = pagerView.dequeueReusableCell(withReuseIdentifier: "cell", at: index) as! YouCellHere

 return cell
}

But I find that this make didSelectItemAt function does't work at all. Only use FSPagerViewCell can work well ,please help!

**Comment by gokberkince** [comment]
how to solve the problem?
