### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by MysteryRan** [WenchaoD/FSPagerView#26]
too much memory leak when i used Instruments to analyze

**Comment by TMTBO** [comment]
yeah, i got the same problem

**Comment by WenchaoD** [comment]
The issue will disappear if the cache of `UICollectionViewLayoutAttributes` is removed, and I can't explain why. It seems that the same thing happened in [CHTCollectionViewWaterfallLayout](https://github.com/chiahsien/CHTCollectionViewWaterfallLayout/issues/163). 

Anyway, the fix can be found [here](https://github.com/WenchaoD/FSPagerView/commit/e5355a29dbcbb3c40d186c3c8a206e7d8b5cbce2). And I'm open to discussion if there are better solutions.

**Comment by MysteryRan** [comment]
DId you not update this change?  i will change your code by myself?
