### ISSUE TITLE
滑动卡片会有偏移？

### ISSUE THREAD

**Issue by cash0211** [WenchaoD/FSPagerView#266]
滑动卡片会有偏移？正常应该居中的，一般滑到第 3 4 张就会偏移了，轻轻波动一下，就正常了？有办法解决吗？

**Comment by tangaowen** [comment]
请问你解决了吗， 我也遇到类似的问题了，谢谢。

**Comment by cash0211** [comment]
> 请问你解决了吗， 我也遇到类似的问题了，谢谢。
源码是没有问题的，我们这里是在`pagerViewWillEndDragging`网络请求加载数据了，应该是动画减速的时候，reloadData 了，你可以局部注释代码看下。
