### ISSUE TITLE
发现一个崩溃问题

### ISSUE THREAD

**Issue by yuhaiping** [WenchaoD/FSPagerView#277]
<img width="1265" alt="截屏2020-04-29下午7 12 34" src="https://user-images.githubusercontent.com/16203703/80589929-a5fa9880-8a4d-11ea-9896-c32545182184.png">

**Comment by yuhaiping** [comment]
@WenchaoD  能帮忙解决下这个问题吗

**Comment by WenchaoD** [comment]
请问这是怎么复现的？

**Comment by yuhaiping** [comment]
> 请问这是怎么复现的？

1. 我是用iglistkit 写了一个页面， 这个页面可根据导航上的按钮切换显示：卡片式和列表式两种UI（卡片式UI有用到你写的控件）
2. 第一次遇到崩溃分析原因： 定时器没有停，banner还在刷新，但是banner的父控件已经释放了（这里的父控件我指的是 iglistkit ListSectionController）
  然后我的解决方法是 ：
     a. 在父控件释放的方法里面停掉定时器，代码如下
if let cell: BannerCollectionViewCell = self.collectionContext?
            .dequeueReusableCell(of: BannerCollectionViewCell.self, for: self, at: 0) as? BannerCollectionViewCell {
            cell.pageView.automaticSlidingInterval = 0
        }
 b. 按钮切换UI：卡片 -> 列表 ，也会把定时器停掉，代码和上面一样
 3. 这两天测试发现还是会crash，快速切换按钮，复现概率比较高，所以我应该还是没找到根本原因
 4. 看奔溃的日志信息是 self.datasource用了强制解包

以上就是我复现的场景，谢谢回复！

**Comment by WenchaoD** [comment]
在主视图被移除的时候定时器应该是停止了的。
方便做个能复现的demo吗？可以发到我的邮箱。最好也能复现定时器的问题。

**Comment by yuhaiping** [comment]
> 候定时器应该是停止了的

我主视图没有移除，一直都在

**Comment by yuhaiping** [comment]
@WenchaoD  复现demo 已经发送你邮箱，请查收，谢谢！

**Comment by WenchaoD** [comment]
你好，你使用的思路是有问题的。
你的pagerView和对应的dataSource生命周期没有绑定的。你的pagerView在cell当中创建的，但是dataSource却设置到sectionController上，当sectionController（dataSource）被释放掉了，但是pagerView还没有被释放，所以找不到dataSource。
正确的做法是将pagerView的dataSource设置到对应的cell上，或者是一个跟cell具备相同生命周期的对象。我在你的demo中将dataSource设置为cell，根本不用stopTimer（那并不是主要原因），就不会出现这个问题。

**Comment by yuhaiping** [comment]
> agerView和对应的dataSource生命周期没有绑定的

好的，我懂了，谢谢！
