### ISSUE TITLE
Problem With Manually Scroll If Add Programmatically

### ISSUE THREAD

**Issue by indrac** [WenchaoD/FSPagerView#28]
I add the view pager manually into my code without using Storyboard, and the views and everything is worked, except for one thing The Scroll. I can't scroll viewpager if I scroll from the center or bottom side, I only can scroll if I touch and scroll them from the top side. Can you fix this?

**Comment by WenchaoD** [comment]
I'm not quite sure what does this mean. Can you demonstrate the problem with a screen recording file(mp4/gif)?

**Comment by indrac** [comment]
I don't know what I just did before, but the problem gone away. And your library works flawlessly. Thanks!

You should open donate for yourself, because help a lot of people.
