### ISSUE TITLE
What is the FSPageView of backgroundView and contentView?

### ISSUE THREAD

**Issue by broccolii** [WenchaoD/FSPagerView#3]
`backgroundView` & `contentView` in FSPageView
I read the source code when the two variables do not understand 
Is it more written?

**Comment by WenchaoD** [comment]
Hi @broccolii For your questions:
1. `contentView` is a content wrapper for the inbuilt UICollectionView. It is always not a bad idea to wrap the whole contents for your control for better extensibility. For example, maybe someday a property `contentInsets` is required.
2. `backgroundView` is a background behind the whole `contentView`.  You would probably want to simply put a background without the pain of adjusting frames or setting up constraints, and for less and cleaner code style. You might be interested in [The backgroundView property of UICollectionView](https://developer.apple.com/reference/uikit/uicollectionview/1618074-backgroundview). 
Hopefully this would help.

**Comment by broccolii** [comment]
Thank you for helping me with this question ~~ 😃
