### ISSUE TITLE
Update for Swift Swift 5.4 for Xcode Version 12.5 (12E262)

### ISSUE THREAD

**Issue by YanSteph** [WenchaoD/FSPagerView#311]
Hi.

This is possible to update FSPagerView for Swift 5.4 for Xcode Version 12.5 (12E262) ?

My error : Module compiled with Swift 5.3.2 cannot be imported by the Swift 5.4 compiler.

Thanks you.

**Comment by Mozahler** [comment]
are you referring to the `FSPagerView` module in the project?
If so, you just need to select its scheme and then compile it.
After that the module has been created with the correct version.
Switch to the scheme that imports this module and it will now work.
