### ISSUE TITLE
Bug: "didSelectItemAt" not called if "shouldHighlightItemAt" always false

### ISSUE THREAD

**Issue by gabriel-dynamo** [WenchaoD/FSPagerView#33]
Hi. It would be great to fix the following bug:
When I set the following:
`func pagerView(_ pagerView: FSPagerView, shouldHighlightItemAt index: Int) -> Bool {
        return false
    }`
then `func pagerView(_ pagerView: FSPagerView, didSelectItemAt index: Int)` is never called.
Of course this is not the normal behaviour: I want to be able to call `didSelectItemAt` but have no highlight when the item is tapped.
Thanks for fixing this bug!
NB: for those having the same issue as I have, you might be solving the issue with attaching a TapGesture to the items. I have not tested it yet though.

**Comment by WenchaoD** [comment]
I don't think this is a bug for the repo. But you can always add the gesture for the item by yourself to get the behavior.

**Comment by mikelsulanjaku** [comment]
This is a real issue. I am experiencing the exact same thing. Also the didHighlight function triggers only randomly and sporadically. It's important to be able to act upon the item selected... Do you plan to have any fix or suggestions for this?

**Comment by mikelsulanjaku** [comment]
Here's a workaround in case somebody else gets stuck on this:
func pagerViewDidScroll(_ pagerView: FSPagerView){
        print(pagerView.currentIndex)
        //Do something according to the current index 
    }
