### ISSUE TITLE
EXC_BAD_ACCESS error=1 on self.pagerView.register

### ISSUE THREAD

**Issue by asciifaceman** [WenchaoD/FSPagerView#35]
It is 1000% possible that I missed something obvious, however my project with just an absolute barebones "just get it to build and run even if it doesn't do anything" implementation (based on readme and glancing at examples) is giving me an `EXC_BAD_ACCESS (error=1, address=0x0)` on the register:

```
    @IBOutlet weak var pagerView: FSPagerView! {
        didSet {
            self.pagerView.register(FSPagerViewCell.self, forCellWithReuseIdentifier: "cell")
        }
    }
```

I've tried to dig around this and figure it out on my own if I was missing something. Checked to ensure I added the class, it was added as a framework, checked any weird build steps etc. 

I am also seeing:

```
2017-04-19 01:02:43.599 flanl[18910:8372737] Unknown class FSPagerView in Interface Builder file.
```

In the runtime log.

----
XCode 8.2
Swift3

**Comment by laznrbfe** [comment]
I think it will help your.
[http://stackoverflow.com/questions/24924966/xcode-6-strange-bug-unknown-class-in-interface-builder-file](http://stackoverflow.com/questions/24924966/xcode-6-strange-bug-unknown-class-in-interface-builder-file)

**Comment by asciifaceman** [comment]
Was fixed after seeing

`SWIFT_CLASS("_TtC11FSPagerView11FSPagerView")`

`FSPagerView` is required in the module field as well.
