### ISSUE TITLE
selectedForegroundView problem with custom FSPagerViewCell

### ISSUE THREAD

**Issue by mhtranbn** [WenchaoD/FSPagerView#37]
hi @WenchaoD  i have problem with selectedForegroundView, when i custom fspagerviewcell, when call scrollToItem (or didSelectItemAt) this fspagerviewcell will have a view empty top, i cant touch most of button on fspagerviewcell. 
https://yadi.sk/i/r2IdG2kI3HXeMU

**Comment by abhishekGour22** [comment]
Hi, @WenchaoD  I am facing the same problem. I hope it will be handled quickly.
I have used a custom cell with the button on it. But unable to perform an action on it. There is empty view added in its superview.

**Comment by WenchaoD** [comment]
Fixed, thanks.

**Comment by hyd00** [comment]
Having same issue. Cannot touch button in custom cell. How to fix?
