### ISSUE TITLE
Custom Cell ?

### ISSUE THREAD

**Issue by bilawal-liaqat** [WenchaoD/FSPagerView#41]
is there any way we can use custom cell instead of "FSPagerViewCell" ?

I created custom class  "slideCell"  and inherited it from  "FSPagerViewCell"  but its not working 

class SliderCell: FSPagerViewCell {
}

**Comment by WenchaoD** [comment]
```swift
pagerView.register(SliderCell.self, forCellWithReuseIdentifier: yourIdentifier)
```

**Comment by bilawal-liaqat** [comment]
@WenchaoD 
I already did this and it was not working 

@IBOutlet weak var pagerView: FSPagerView! {
        didSet {
        
            self.pagerView.register(SliderCell.self, forCellWithReuseIdentifier: "cell")
            
            self.pagerView.itemSize = .zero
        }
    }

**Comment by bilawal-liaqat** [comment]
I fixed it using 
 self.pagerView.register(UINib(nibName: "SliderCell", bundle: nil), forCellWithReuseIdentifier: "cell")

**Comment by iad24** [comment]
thanks @bilawal-liaqat
