### ISSUE TITLE
Unable to Interact with buttons in cell

### ISSUE THREAD

**Issue by singhdd93** [WenchaoD/FSPagerView#43]
I have a custom cell which has buttons, but I am unable to interact with buttons at all.

**Comment by atom2ueki** [comment]
did you replace the cell over the original one? you can try to use a tag on your button to detect it's been clicked

**Comment by WenchaoD** [comment]
Try add your button on `contentView` of your custom cell.

**Comment by mrlazy1324** [comment]
Hello @WenchaoD , 

Your library is so good It's very helpful.

But I face the issue of "not getting any button clicks"

Steps of my project 
1) I have one view controller
2) That view controller contains one full view tableview controller
3) In that tableview particular at 0 index FSPagerView available
4) For FSPagerView I make one my custom view (CustomView.swift and CustomView.xib) using xib, CustomView.Swift class derive from FSPagerViewCell.
5) In that CustomView.xib I have 3 buttons.
6) When I run the application all UI I getting as per my result but I am not getting any buttons clicks

For clicks 
1) I added all outlets of UIButton
2) For all buttons, I added selectors in the method of cellforItemAt (public func pagerView(_ pagerView: FSPagerView, cellForItemAt index: Int) -> FSPagerViewCell)
3) But I am not getting any buttons selector.
4) When I press the button only getting a click in didSelectItemAt (func pagerView(_ pagerView: FSPagerView, didSelectItemAt index: Int))
5) Please help me with these buttons clicks, all views have userinteraction = true 
I spent lots of time to fetch clicks of buttons but I don't get any clicks.

**Comment by creative-dev-lab** [comment]
This might solve the problem.
In `public func pagerView(_ pagerView: FSPagerView, cellForItemAt index: Int) -> FSPagerViewCell` function, try to add the code below before return the cell.
`yourcell.contentView.isUserInteractionEnabled = false`

Guess is that the cell selection was hijacking the touch event

**Comment by sjacs5537** [comment]
Same issue encountered, it solve the problem.

Don't know why it need to set `isUserInteractionEnabled = false` to make the button action works, is it a bug?

> This might solve the problem.
> In `public func pagerView(_ pagerView: FSPagerView, cellForItemAt index: Int) -> FSPagerViewCell` function, try to add the code below before return the cell.
> `yourcell.contentView.isUserInteractionEnabled = false`
> 
> Guess is that the cell selection was hijacking the touch event

**Comment by creative-dev-lab** [comment]
@sjacs5537 , Happy to know it solves your problem.
There are several possibilities for this issue.
We probably need to double-check the structure of the FSPagerView. The structure probably could have a second embedded cell, rather than just one. or there might be other possibilities as well.

I'd like to look into the code for this repository, but for now, I am deadly busy. I will surely look into this one.
