### ISSUE TITLE
Centralize cell

### ISSUE THREAD

**Issue by zionix357** [WenchaoD/FSPagerView#49]
![simulator screen shot 6 de jun de 2017 19 40 18](https://user-images.githubusercontent.com/5609018/26855184-fa9b9efc-4aef-11e7-8145-3337e6d85869.png)

How do I centralize?

Example:
![simulator screen shot 6 de jun de 2017 19 40 01](https://user-images.githubusercontent.com/5609018/26855191-06ff094a-4af0-11e7-9612-2b7894faa6c3.png)

**Comment by WenchaoD** [comment]
Centralization is the default behavior. Can u provide a demo which reproduce your issue?
