### ISSUE TITLE
Need indexPathForItemAtPoint(_ point: CGPoint) methods

### ISSUE THREAD

**Issue by NameX44** [WenchaoD/FSPagerView#50]
Hi,

Is it possible that you implement the following function of the UICollectionView : 

func indexPathForItemAtPoint(_ point: CGPoint) -> NSIndexPath?

It is needed when you add a custom view with a target in a button for exemple to get the indexPath of the clicked button.

Thanks.

**Comment by WenchaoD** [comment]
You can put the `index` as the `tag` of your button.

**Comment by NameX44** [comment]
That's already what I did but that's not the way we should do it.
