### ISSUE TITLE
add next and previous button

### ISSUE THREAD

**Issue by Emy87aa** [WenchaoD/FSPagerView#53]
If I want to scroll next and previous images by buttons too 
what the action will be in my next & previous buttons?

**Comment by tkirby** [comment]
I ended up doing something like this to get it to work:

`    @IBAction func nextSlide()
    {
        let nextIndex = pagerView.currentIndex + 1 < numberOfItems(in:self.pagerView) ? pagerView.currentIndex + 1 : 0
        
        pagerView.scrollToItem(at: nextIndex, animated: true)
    }
    
    @IBAction func previousSlide()
    {
        let prevIndex = pagerView.currentIndex > 0 ? pagerView.currentIndex - 1 : numberOfItems(in:self.pagerView) - 1
        
        pagerView.scrollToItem(at: prevIndex, animated: true)
    }`
