### ISSUE TITLE
ReloadData() disables interaction on custom PagerViewCell

### ISSUE THREAD

**Issue by lucasgerard** [WenchaoD/FSPagerView#62]
Hey,

I'm reloading pagerView data after unwinding from another viewController, but after calling `reloadData`, an extra layer seems to be added on each cell, disabling interactions with the cell. Any idea where it may come from? Thanks!!

Please find below a screenshot of the view hierarchy, before and after calling `reloadData`.

![after](https://user-images.githubusercontent.com/5589858/27923676-8138286c-627f-11e7-8fb4-af9d1ed831be.png)
![before](https://user-images.githubusercontent.com/5589858/27923678-8138bf3e-627f-11e7-89f5-8be6981c6f89.png)

**Comment by WenchaoD** [comment]
1. Are you using latest `0.5.5`?
2. Can you show an example project link for the issue?

**Comment by lucasgerard** [comment]
Hey, seems to be fixed indeed in last version, sorry! Thanks

**Comment by taimoorsuleman** [comment]
facing same issue in 0.8.3 version
