### ISSUE TITLE
how can i set interitemSpacing in linear case

### ISSUE THREAD

**Issue by starkite** [WenchaoD/FSPagerView#67]
how can i set interitemSpacing in linear case

thanks

**Comment by phucnd0604** [comment]
i have same issue, please support

**Comment by alexanderkhitev** [comment]
+1

**Comment by trejdych** [comment]
+1

**Comment by SHRashad** [comment]
+1

**Comment by bolagong** [comment]
+1

**Comment by z234009184** [comment]
+1

**Comment by z234009184** [comment]
@WenchaoD

**Comment by bluerainxty** [comment]
subclass FSPagerViewTransformer and override func proposedInteritemSpacing() -> CGFloat
work for me, you can try @starkite

**Comment by starkite** [comment]
@bluerainxty 
Thx!!!  it's work for me, too

**Comment by nilhy** [comment]
@starkite  Please tell me the detailed steps

**Comment by nilhy** [comment]
@starkite  I inherited FSPagerViewTransformer and rewrote the proposedInteritemSpacing but it still doesn't work

**Comment by mayqiyue** [comment]
@starkite it doesn't work, I have came cross the source cdoes.  proposedInteritemSpacing will never be called in linear type.

**Comment by limtyty** [comment]
@mayqiyue 
pagerView.transformer = NoVerticalScalePagerViewTransformer(type: .linear)

//Create Class

class NoVerticalScalePagerViewTransformer: FSPagerViewTransformer {
override func applyTransform(to attributes: FSPagerViewLayoutAttributes) {
      guard let pagerView = self.pagerView else {
         return
      }
      let position = attributes.position
      let scrollDirection = pagerView.scrollDirection
      let itemSpacing = (scrollDirection == .horizontal ? attributes.bounds.width : attributes.bounds.height) + self.proposedInteritemSpacing()
      if self.type == .linear {
         guard scrollDirection == .horizontal else {
            // This type doesn't support vertical mode
            return
         }
         let scale = max(1 - (1-self.minimumScale) * abs(position), self.minimumScale)
         let scaleY = max(1 - (1-self.minimumScale) * abs(position), 0.95)
         // let transform = CGAffineTransform(scaleX: scale, y: scale)
         // **Modify here**
         print(proposedInteritemSpacing())
         let transform = CGAffineTransform(scaleX: scale, y: scaleY)
         attributes.transform = transform
         let alpha = (self.minimumAlpha + (1-abs(position))*(1-self.minimumAlpha))
         attributes.alpha = alpha
         let zIndex = (1-abs(position)) * 10
         attributes.zIndex = Int(zIndex)
      } else {
         super.applyTransform(to: attributes)
      }
   }
 override func proposedInteritemSpacing() -> CGFloat {
      return -50
   }
}

**Comment by TiagoMaiaL** [comment]
Couldn't this be automatic, by reading the pager's `interitemSpacing` property?
