### ISSUE TITLE
How to set RTL Title for each slide ?

### ISSUE THREAD

**Issue by arsanjani** [WenchaoD/FSPagerView#7]
hi there
I wanna each slide has a right-to-left title, how can i do that ?

**Comment by WenchaoD** [comment]
Hi @arsanjani 
There is no direct open interface for this feature. But maybe you can try this workaround:
1.  Change the `textAlignment` of the textLabel

```swift
cell.textLabel.textAlignment = .right
```

2. Revert your string by ***Reverted-enumeration of the characters and append them to a new string***. [This category](https://gist.github.com/Shilo/6409077) might help.
