### ISSUE TITLE
Can't proceed too many errors

### ISSUE THREAD

**Issue by anirudhamahale** [WenchaoD/FSPagerView#70]
I am getting the following errors
![screen shot 2017-08-22 at 1 42 01 pm](https://user-images.githubusercontent.com/16848003/29555313-e021289e-873f-11e7-993a-66063884f5e8.png)

**Comment by pieterclaerhout** [comment]
You shouldn't name your test project `FSPagerView`. Rename it to e.g. `FSPagerViewerDemo` and the problem should be gone.
