### ISSUE TITLE
about shadows..

### ISSUE THREAD

**Issue by Kejiasir** [WenchaoD/FSPagerView#72]
hi, how to remove the shadow on the item?

**Comment by Mahan3340** [comment]
how did you removed the shadows ?

**Comment by Kejiasir** [comment]
@Mahan3340 `[cell.contentView.layer setShadowRadius:0];`

**Comment by sajib-ghoshInnofied** [comment]
Hi,

Could you please let me know how to change the color of the shadow? 
I tried the code: cell.containerView.layer.shadowColor = UIColor.red.cgColor, 
But not working, still showing the black show.
Thanks in advance.

**Comment by awais-ijaz-brainx** [comment]
cell.contentView.layer.shadowColor = UIColor.clear.cgColor 
This is how you can remove the shadow color
