### ISSUE TITLE
Compile error when using Xcode 9 with swift 4.

### ISSUE THREAD

**Issue by ufosky** [WenchaoD/FSPagerView#76]
I'm trying to upgrade my project to use xcode 9 and swift 4,but has error when compile this library.
![image](https://user-images.githubusercontent.com/801838/30385613-4803ccf4-98da-11e7-9bff-e9229b35594f.png)

**Comment by chickdan** [comment]
See PR #80

**Comment by WenchaoD** [comment]
Fixed, thanks.
