### ISSUE TITLE
Crash issue after  update project to Xcode9 GM Swift 4.0

### ISSUE THREAD

**Issue by csmarku** [WenchaoD/FSPagerView#77]
Hi there,

When I update my project from Xcode8 swift 3.0 to Xcode9 GM  Swift 4.0,
there is a new issue make app crash when launch.

crash Info:
Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<XX.FSPagerView 0x7fa56ad21e00> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key dataSource.'
##
and the source code i change
IN FSPagerView.swift
` open internal(set) dynamic var currentIndex: Int = 0`
to 
`@objc open internal(set) dynamic var currentIndex: Int = 0`

` let scrollOffset = Double(contentOffset.divided(by: self.collectionViewLayout.itemSpacing))`
to
`let scrollOffset = Double(contentOffset / self.collectionViewLayout.itemSpacing)`
##
IN FSPageControl.swift
add 
            `case .leading:
                return 0
            case .trailing:
                let contentWidth = diameter*CGFloat(self.numberOfPages) + CGFloat(self.numberOfPages-1)*spacing
                return contentView.frame.width - contentWidth
            }`
to `open override func layoutSublayers(of layer: CALayer){}`

##
Thanks

**Comment by sumeshd** [comment]
I facing the same issue, please help.

**Comment by sumeshd** [comment]
Request you to please reply. We are stuck on a critical point.

**Comment by chickdan** [comment]
See PR #80

**Comment by WenchaoD** [comment]
Fixed, thanks.
