### ISSUE TITLE
Initial index

### ISSUE THREAD

**Issue by indieSoftware** [WenchaoD/FSPagerView#79]
There seems no possibility to set an initial index for the current item right in setting up the pager view. So it's not possible to start the pager view at a specific position rather than always with the first item.

The FSPagerView provides a function `scrollToItem(at index: Int, animated: Bool)` to scroll to a specific item. So after setting up the pager view and registering some cells I want to scroll without animation to a specific index (before the first frame has rendered), but I get an exception, that the index is out of bounds of the number of items the collection view has. That's because the `numberOfItems` is still 0 because the layout of the collection view hasn't yet evaluated its data source methods.

So the FSPagerView should either have a property like `initialIndex` or `scrollToItem(at:animated:)` should handle the scrolling to the index right after the collection view layout has been prepared if called before.

As a current workaround I can call `scrollToItem(at:animated:)` via GCD with zero delay in the next frame, so only one frame the wrong item will be shown.

**Comment by WenchaoD** [comment]
Do `scrollToItem(at:animated:)` in `viewDidLayoutSubviews:` and make sure it executes only one time. There is no `initialIndex ` in `UICollectionView`, so it won't bother.

**Comment by kornha** [comment]
I'm not sure how this solution works. The viewDidLayoutSubviews gets called before the numberOfItemsAt gets called. I still get an error of an index OOB.

**Comment by kornha** [comment]
Must be in main dispatch:             

DispatchQueue.main.async {
self.pagerView.scrollToItem(at: index, animated: false)
 }

**Comment by kornha** [comment]
But with this solution I get one frame incorrectly shown.

**Comment by xinnai** [comment]
I got same problems ,I put scrollToItem in DispatchQueue and viewDidLayoutSubviews but still doesn't work at all

**Comment by troZee** [comment]
```
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)

        pagerView.setNeedsLayout()
        pagerView.layoutIfNeeded()

        pagerView.scrollToItem(at: 1, animated: true)
     }
```
