### ISSUE TITLE
Xcode 9 with iOS 11 target in iMessage template leads to the following crashing issue, when view FSPage view is called.

### ISSUE THREAD

**Issue by sumeshd** [WenchaoD/FSPagerView#83]
Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIView 0x103f1ad50> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key dataSource.

**Comment by WenchaoD** [comment]
Try `0.7.0`?

**Comment by sumeshd** [comment]
That is what we used yesterday. We used Pod to pull 0.7.0 All prebuild issues were resolved but during execution, we faced the above-mentioned issue.

**Comment by WenchaoD** [comment]
Have you tried remove `dataSource` and `delegate` properties from Storyboard and link again?

**Comment by sumeshd** [comment]
Yup, did that, no help.

**Comment by sumeshd** [comment]
Any other suggestings @WenchaoD ?

**Comment by sumeshd** [comment]
@WenchaoD This was a problem with a conflict of another library's AWS core. We removed all libraries and downloaded it again, FSPage now works perfectly.

**Comment by ninobc** [comment]
Hi @sumeshd ,

I am having the same issue. However, I don't really understand why a conflict would occur in the first place. Did you permanently remove all other libraries or did u just remove them all then add them again? Any help would be greatly appreciated :)

**Comment by sumeshd** [comment]
Hi @ninobc 

We modified our podfile and removed all libraries except for FSPage, then ran a pod install. 
This deleted all other libraries. Then included all other libraries in our podfile and installed it again. This removed conflicts of any sort and solved the issue. 

Things to note: we had modified a static pod framework, possibly that was causing the conflict.
