### ISSUE TITLE
Changing orientation changes the pager index

### ISSUE THREAD

**Issue by indieSoftware** [WenchaoD/FSPagerView#91]
The pager index changes when rotating the device into landscape.
Steps to reproduce:
Open the demo project provided by this lib.
Choose Banner example.
Don't change any parameters, but rotate the device from portrait to landscape.
Rotate back to portrait.

Expected behavior: The image should still be the first one in the list (with 00 down left in the corner).
Current behavior: The image has changed and also the index of the current item.

Follw-up bug:
Deactivate the switch for "Infinite".
Scroll to the end of the image list (the one with the 66 in the lower left).
Rotate the device from portrait to landscape.

Expected behavior: The image should be still the last one (with the 66 in the corner) regardless of the bug mentioned before.
Current behavior: The image has changed (to 55) even without rotating back into portrait.

**Comment by LukA888** [comment]
Same here.

**Comment by WenchaoD** [comment]
Fixed.
