### ISSUE TITLE
Horizontal Mode - Clickable next, prev item

### ISSUE THREAD

**Issue by ozibrahim** [WenchaoD/FSPagerView#95]
Firstly, thanks for user friendly library.
I'm using horizontal, and there is 3 items in screen.
I want to user can click next and prev item and change current item. 
Is it possible with small code, or am i asking feature request?

Thanks,

**Comment by EstebanVallejo** [comment]
@ozibrahim hey, I'm doing that with this code

`func pagerView(_ pagerView: FSPagerView, didSelectItemAt index: Int) {
    guard index == pagerView.currentIndex else {
      pagerView.scrollToItem(at: index, animated: true)
      return
    }

// Handle selection of currentIndex here
  }`

By scrolling to the non-current item, it will become the new currentItem.

**Comment by ozibrahim** [comment]
@EstebanVallejo thanks for your help, i've moved another library, but your code works like charm.
